#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code only if STDERR is bound to a TTY.
if [ -e ~/txt/bible.txt ]; then
  shuf -n 1 ~/txt/bible.txt
fi
