#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# Functions
#

ssh() {
  # Set the path to the SSH directory.
  _ssh_dir="$HOME/.ssh"

  # Set the path to the environment file if not set by another module.
  _ssh_agent_env="${_ssh_agent_env:-${TMPDIR:-/tmp}/ssh-agent.env}"

  # Set the path to the persistent authentication socket.
  _ssh_agent_sock="${TMPDIR:-/tmp}/ssh-agent.sock"

  # Start ssh-agent if not started.
  if [[ ! -S "$SSH_AUTH_SOCK" ]]; then
    # Export environment variables.
    source "$_ssh_agent_env" 2> /dev/null

    # Start ssh-agent if not started.
    if ! ps -U "$LOGNAME" -o pid,ucomm | grep -q -- "${SSH_AGENT_PID:--1} ssh-agent"; then
      eval "$(ssh-agent | sed '/^echo /d' | tee "$_ssh_agent_env")"
    fi
  fi

  # Create a persistent SSH authentication socket.
  if [[ -S "$SSH_AUTH_SOCK" && "$SSH_AUTH_SOCK" != "$_ssh_agent_sock" ]]; then
    ln -sf "$SSH_AUTH_SOCK" "$_ssh_agent_sock"
    export SSH_AUTH_SOCK="$_ssh_agent_sock"
  fi

  # Load identities.
  if ssh-add -l 2>&1 | grep -q 'The agent has no identities'; then
    zstyle -a ':prezto:module:ssh:load' identities '_ssh_identities'
    if (( ${#_ssh_identities} > 0 )); then
      ssh-add "$_ssh_dir/${^_ssh_identities[@]}" 2> /dev/null
    else
      ssh-add 2> /dev/null
    fi
  fi

  # Clean up.
  unset _ssh_{dir,identities} _ssh_agent_{env,sock}

  # Execute ssh
  /usr/bin/ssh $*
}

#
# Aliases
#

alias ls="ls ${LS_OPTIONS}"
alias ll='ls -la'
alias rm="nocorrect rm"
alias jsonpp='python -mjson.tool'
#alias search='find . -print0 | xargs -0 -- grep'
#alias search=ack
alias search=ag
alias vless='/usr/share/vim/vim??/macros/less.sh'
alias bible='shuf -n 1 ~/txt/bible.txt'
alias grep='grep --color'
alias vim=nvim
alias gtop=glances
eval $(thefuck --alias)

#
# tmuxifier
#
eval "$(tmuxifier init -)"

#
# Prompt
#

autoload -Uz promptinit
promptinit
# prompt repa

setopt interactivecomments

# fzf
# export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*" --glob "!.hg/*"'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
