# ============================================================================
# GENERAL OPTIONS
# ============================================================================

# Mouse support and terminal settings
set -g mouse on
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -g status-position bottom
set -g set-clipboard on
set -g detach-on-destroy off  # Don't exit from tmux when closing a session
setw -g xterm-keys on
set -sg escape-time 0         # Faster command sequences
set -sg repeat-time 600       # Increase repeat timeout
set -s focus-events on
set -q -g status-utf8 on
setw -q -g utf8 on
set -g history-limit 10000     # Increase scrollback buffer size

# Window and pane handling
set -g base-index 1                   # Start windows at 1, not 0
setw -g pane-base-index 1             # Start panes at 1, not 0
set-window-option -g pane-base-index 1
set-option -g renumber-windows on     # Renumber windows when one is closed
set-option -g allow-rename off        # Don't rename windows automatically
set -g set-titles on                  # Allow terminal titles to be set by applications
set -g display-panes-time 800
set -g display-time 1000
set -g status-interval 10             # Update status line every 10 seconds

# Enable passthrough
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

## Keys
set -g extended-keys on
set -g extended-keys-format csi-u
set -g prefix2 C-a
bind a send-prefix -2
unbind r
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded ☺️"

# windows
bind - split-window -v -c "#{pane_current_path}"
bind / split-window -h -c "#{pane_current_path}"
bind C-a last-window
bind c new-window -c "#{pane_current_path}"
bind C-c new-window -c "#{pane_current_path}"

# pane navigation
bind -r h select-pane -L  # move left
bind -r t select-pane -D  # move down
bind -r n select-pane -U  # move up
bind -r s select-pane -R  # move right
bind -n M-Left select-pane -L  # move left with Alt+left
bind -n M-Right select-pane -R  # move right with Alt+M-Right
bind -n M-Down select-pane -D  # move down with Alt+M-Down
bind -n M-Up select-pane -U  # move up with Alt+M-Up
bind > swap-pane -D       # swap current pane with the next one
bind < swap-pane -U       # swap current pane with the previous one

bind-key x kill-pane

# pane resizing
bind -r H resize-pane -L 2  # resize left
bind -r T resize-pane -D 2  # resize down
bind -r N resize-pane -U 2  # resize up
bind -r S resize-pane -R 2  # resize right

# copy buffers
bind b list-buffers
bind p paste-buffer
bind P choose-buffer

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'alexwforsythe/tmux-which-key'
# set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'egel/tmux-gruvbox'

# gruvbox theme
set -g @tmux-gruvbox 'dark'

# Sesh
bind-key Tab run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

# ============================================================================
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

