# History
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt INC_APPEND_HISTORY

# Completion
autoload -Uz compinit
compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# Carapace
export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense'
zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
source <(carapace _carapace)

# Navigation
# setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS

# Corrections
setopt CORRECT

# Useful aliases
#alias ls='eza --icons'
alias ls='ls --color=auto --group-directories-first -F -b -T 0'
alias ll='eza -la --icons --git'
alias tree='eza --tree'
alias vim='nvim'
alias cat='bat'
alias ping='prettyping --nolegend'
alias lg='lazygit'
alias watch='viddy'

# AI agent aliases
alias nclaude='nono run --allow-cwd --profile claude-code -- claude'
alias ngemini='echo TODO'
alias npi='echo TODO'

# Plugins (install these first)
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# fzf (if installed)
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Atuin - history
eval "$(atuin init zsh)"

# Zoxide
eval "$(zoxide init zsh)"

# Direnv
eval "$(direnv hook zsh)"

# Accept autosuggestion with Ctrl+Space
bindkey '^ ' autosuggest-accept

# Prompt (using starship)
# eval "$(starship init zsh)"
# Prompt (using oh-my-posh)
eval "$(oh-my-posh init zsh --config ~/config/zsh/repa.omp.json)"

